name: .NET Core Build & Test

on:
  push:
    branches: [ "develop", "master", "release/*" ]
  pull_request:
    branches: [ "develop", "master", "release/*" ]

env:
  Solution_Path: "Solution/MUSICBase.sln"

jobs:        
  build:
    name: Build & Test
    runs-on: windows-latest
    
    strategy:
      matrix:
        configuration: [ Release ]
        dotnet-version: [ '8.x' ]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the GitTools extension
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        preferLatestVersion: true

    # Determine version with GitVersion  
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0
      
    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
        
    # Restore the solution
    - name: Restore the solution
      run: dotnet restore $env:Solution_Path

    # Build the solution
    - name: Build the solution
      run: dotnet build $env:Solution_Path -c $env:Configuration --no-restore
      env:
        Configuration: ${{ matrix.configuration }}

    # Execute all tests in the solution
    - name: Execute tests
      run: dotnet test $env:Solution_Path -c $env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
